name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2025-07-29"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-db"
database_id = "70dbc460-87d3-452c-9143-a883e3d10dcc"
